classDiagram
    direction TB

    class models.Model {
        <<Django 기본 클래스>>
    }

    class AbstractPost {
        +User author
        +String subject
        +TextField content
        +DateTimeField create_date
        +DateTimeField modify_date
        +PositiveIntegerField view_count
        +ManyToManyField voter
        <<abstract>>
    }

    class AbstractComment {
        +User author
        +TextField content
        +DateTimeField create_date
        +DateTimeField modify_date
        +ManyToManyField voter
        <<abstract>>
    }

    class SimilarityPost {
        +ImageField image1
        +ImageField image2
    }
    
    class SimilarityComment {
        +ForeignKey post (SimilarityPost)
        +ImageField image1
        +ImageField image2
    }

    class DetectionPost {
        +ImageField image1
    }
    
    class DetectionComment {
        +ForeignKey post (DetectionPost)
        +ImageField image1
    }

    models.Model <|-- AbstractPost : 상속
    models.Model <|-- AbstractComment : 상속
    AbstractPost <|-- SimilarityPost : 상속
    AbstractPost <|-- DetectionPost : 상속
    AbstractComment <|-- SimilarityComment : 상속
    AbstractComment <|-- DetectionComment : 상속
    SimilarityPost "1" --> "many" SimilarityComment : has
    DetectionPost "1" --> "many" DetectionComment : has

%% ############################################################################################################
classDiagram
    class BaseExtraContextMixin {
        +get_context_data(**kwargs) : dict
    }
    class BaseListView {
        +paginate_by: int
        +template_name: str
        +search_fields: list
        +get_queryset() : QuerySet
        +get_context_data(**kwargs) : dict
    }
    class BaseReadView {
        +model: Model
        +template_name: str
        +context_object_name: str
        +get_context_data(**kwargs) : dict
        +_process_comments(comments) : list
        +_get_comment_messages(comments) : dict
    }
    class BaseFormMixin {
        +model: Model
        +form_class: Form
        +template_name: str
        +get_context_data(**kwargs) : dict
        +_save_uploaded_images(obj) : None
        +form_valid(form) : obj
    }
    class BaseCreateView {
        +form_valid(form) : HttpResponseRedirect
    }
    class BaseUpdateView {
        +extra_tags_byME: str
        +form_valid(form) : HttpResponseRedirect
    }
    class BaseDeleteView {
        +get(request, *args, **kwargs) : HttpResponse
        +delete(request, *args, **kwargs) : HttpResponse
    }
    class BaseVoteView {
        +get_redirect_url(*args, **kwargs) : str
    }
    
    class SimilarityPostListView {
        +model: Model
        +template_name: str
        +search_fields: list
    }

    class SimilarityPostReadView {
        +model: Model
        +template_name: str
    }

    class SimilarityPostCreateView {
        +model: Model
        +form_class: Form
        +success_url: str
        +template_name: str
        +form_valid(form) : HttpResponseRedirect
    }

    class SimilarityPostUpdateView {
        +model: Model
        +form_class: Form
        +success_url: str
        +template_name: str
    }

    class SimilarityPostDeleteView {
        +model: Model
        +success_url: str
    }

    class SimilarityPostVoteView {
        +model: Model
        +success_url: str
    }

    BaseExtraContextMixin <|-- IndexView
    TemplateView <|-- IndexView

    ListView <|-- BaseListView

    BaseExtraContextMixin <|-- BaseExtraContextMixin

    LoginRequiredMixin <|-- BaseFormMixin
    BaseExtraContextMixin <|-- BaseFormMixin

    BaseFormMixin <|-- BaseCreateView
    CreatView <|-- BaseCreateView

    DetailView <|-- BaseReadView

    BaseFormMixin <|-- BaseUpdateView
    UpdateView <|-- BaseUpdateView

    LoginRequiredMixin <|-- BaseDeleteView
    DeleteView <|-- BaseDeleteView

    LoginRequiredMixin <|-- BaseVoteView
    RedirectView <|-- BaseVoteView


    BaseExtraContextMixin <|-- SPostECMixin 

    SPostECMixin <|-- SimilarityPostListView
    SPostECMixin <|-- SimilarityPostCreateView
    SPostECMixin <|-- SimilarityPostReadView
    SPostECMixin <|-- SimilarityPostUpdateView
    SPostECMixin <|-- SimilarityPostDeleteView
    SPostECMixin <|-- SimilarityPostVoteView

    BaseListView <|-- SimilarityPostListView
    BaseCreateView <|-- SimilarityPostCreateView
    BaseReadView <|-- SimilarityPostReadView
    BaseUpdateView <|-- SimilarityPostUpdateView
    BaseDeleteView <|-- SimilarityPostDeleteView
    BaseVoteView <|-- SimilarityPostVoteView


%% ############################################################################################################

